### ISSUE TITLE
node 6.3.1 : SyntaxError: Unexpected string

### ISSUE THREAD

**Issue by leviwheatcroft** [dodo/node-unicodetable#26]
```
> require 'unicode'
SyntaxError: Unexpected string
    at Object.exports.createScript (vm.js:47:10)
    at REPLServer.defaultEval (repl.js:255:25)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:477:10)
    at emitOne (events.js:101:20)
    at REPLServer.emit (events.js:188:7)
    at REPLServer.Interface._onLine (readline.js:232:10)
    at REPLServer.Interface._line (readline.js:574:8)
    at REPLServer.Interface._ttyWrite (readline.js:851:14)
>
```

If you dump categories/So.js in jsbeautifier.org or something, you get something like this:

```
    12214: {
        "value": "2FB6",
        "name": "KANGXI RADICAL FLY",
        "category": "So",
        "class": "0",
        "bidirectional_category": "ON",
        "mapping": "<compat> 98DB",
        "decimal_digit_value":  ","
        digit_value ":"
        ","
        numeric_value ":"
        ","
        mirrored ":"
        N ","
        unicode_name ":"
        ","
        comment ":"
        ","
        uppercase_mapping ":"
        ","
        lowercase_mapping ":"
        ","
        titlecase_mapping ":"
        ","
        symbol ":"\
        u2FB6 "}
```

everything after the "decimal_digit_value" line is not interpreted correctly.

**Comment by leviwheatcroft** [comment]
false alarm sorry.
